const fs = require('node:fs');
const path = require('node:path');
const { marked } = require('marked');
const sharp = require('sharp');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const write = (file, data) => { const dest = path.join(root, file); fs.mkdirSync(path.dirname(dest), { recursive: true }); fs.writeFileSync(dest, data); };
const esc = text => String(text).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const site = JSON.parse(read('content/site.json'));
const origin = new URL(site.url).origin;
const template = read('templates/blog.html');
marked.use({ gfm: true, breaks: false });

function parsePost(filename) {
  const source = read('content/posts/' + filename).replace(/\r\n/g, '\n');
  const match = source.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error(filename + ': missing front matter');
  const meta = {};
  for (const line of match[1].split('\n')) {
    const pair = line.match(/^(\w+):\s*(.+)$/);
    if (!pair) throw new Error(filename + ': invalid metadata line');
    meta[pair[1]] = JSON.parse(pair[2]);
  }
  const slug = filename.replace(/\.md$/, '');
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error('Invalid slug: ' + slug);
  for (const key of ['title','date']) if (typeof meta[key] !== 'string' || !meta[key].trim()) throw new Error(filename + ': missing ' + key);
  if (!/^\d{4}(?:\.(?:0[1-9]|1[0-2]))?(?:\.(?:0[1-9]|[12]\d|3[01]))?$/.test(meta.date)) throw new Error(filename + ': invalid date');
  if (meta.poem !== undefined && typeof meta.poem !== 'boolean') throw new Error(filename + ': poem must be boolean');
  const body = match[2].trim();
  const count = body.replace(/\s|^#+ /gm, '').length;
  const [year, month=0, day=0] = meta.date.split('.').map(Number);
  return { ...meta, slug, body, count, key: year*10000 + month*100 + day, url: '/blog/posts/' + slug + '/', image: '/assets/share/' + slug + '.png' };
}

function metadata(title, description, url, image, type = 'website') {
  return `<title>${esc(title)}</title>
${description ? `<meta name="description" content="${esc(description)}">` : ''}
<link rel="canonical" href="${esc(origin + url)}">
<meta property="og:locale" content="zh_CN">
<meta property="og:site_name" content="${esc(site.name)}">
<meta property="og:type" content="${type}">
<meta property="og:url" content="${esc(origin + url)}">
<meta property="og:title" content="${esc(title)}">
${description ? `<meta property="og:description" content="${esc(description)}">` : ''}
<meta property="og:image" content="${esc(origin + image)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${esc(title + ' · 颗粒书封')}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(title)}">
${description ? `<meta name="twitter:description" content="${esc(description)}">` : ''}
<meta name="twitter:image" content="${esc(origin + image)}">`;
}

function page({ title, description, url, image='/assets/share/grain.png', type='website', content, kind }) {
  const replacements = { META:metadata(title,description,url,image,type), PAGE:kind, CONTENT:content, YEAR:new Date().getFullYear() };
  const html = template.replace(/\{\{(META|PAGE|CONTENT|YEAR)\}\}/g, (_, key) => replacements[key]);
  return '<!-- Generated by scripts/build.cjs. Edit content/, templates/ or assets/ instead. -->\n' + html.replace('id="navShelf"',`id="navShelf" aria-current="${kind==='shelf'?'page':'false'}"`).replace('id="navPhotos"',`id="navPhotos" aria-current="${kind==='photos'?'page':'false'}"`);
}

const palette = ['#4E3E32','#6E4F3C','#A98A62','#D9CFBA','#E9E3D3','#5B614F','#41494A','#8E8B81','#4D5665','#303845'];
const wrap = (text, limit) => { const chars = Array.from(text); const lines=[]; for (let i=0;i<chars.length;i+=limit) lines.push(chars.slice(i,i+limit).join('')); return lines; };
async function cover(title, date, file, index) {
  const color = palette[index % palette.length];
  const lines = wrap(title, 13);
  const size = lines.length > 2 ? 43 : 54;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
<rect width="1200" height="630" fill="#F1EFE9"/>
<path d="M52 52H1148V578H52Z" fill="none" stroke="#C9C2B2"/>
<rect x="0" y="0" width="28" height="630" fill="${color}"/>
<rect x="820" y="88" width="270" height="454" rx="5" fill="${color}"/>
<path d="M842 88V542M852 88V542M864 110H1070M864 520H1070" stroke="#F1EFE9" stroke-opacity=".3"/>
<g font-family="Microsoft YaHei, Noto Sans CJK SC, sans-serif" fill="#23241F">
<text x="88" y="120" font-size="19" letter-spacing="5">颗粒 / GRAIN</text>
${lines.map((line,i)=>`<text x="88" y="${245+i*76}" font-size="${size}" font-weight="600">${esc(line)}</text>`).join('')}
<text x="88" y="477" font-size="21" fill="#73746A">${esc(date)} · Max Xiang</text>
<text x="88" y="523" font-size="17" letter-spacing="3" fill="#73746A">物件、动作、温度、声音</text>
</g><rect x="993" y="434" width="52" height="62" rx="2" fill="#A93D2A"/>
<text x="1019" y="460" text-anchor="middle" font-family="Microsoft YaHei, Noto Sans CJK SC, sans-serif" font-size="20" fill="#F1EFE9">颗<tspan x="1019" dy="25">粒</tspan></text>
</svg>`;
  write(file, await sharp(Buffer.from(svg)).png().toBuffer());
}

async function build() {
  const posts = fs.readdirSync(path.join(root,'content/posts')).filter(f=>f.endsWith('.md')).map(parsePost).sort((a,b)=>b.key-a.key || a.slug.localeCompare(b.slug));
  if (!posts.length) throw new Error('No posts found');
  // Remove only previously generated post directories recorded by our own manifest.
  const manifestPath = path.join(root,'blog/posts/manifest.json');
  if (fs.existsSync(manifestPath)) {
    const old = JSON.parse(fs.readFileSync(manifestPath,'utf8'));
    for (const slug of old) if (/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug) && !posts.some(p=>p.slug===slug)) {
      const file = path.join(root,'blog/posts',slug,'index.html');
      if (fs.existsSync(file) && fs.readFileSync(file,'utf8').startsWith('<!-- Generated by scripts/build.cjs.')) fs.unlinkSync(file);
    }
  }
  const items = posts.map((p,i)=>{
    const width=Math.round(Math.min(122,Math.max(54,54+(Math.log10(Math.max(p.count,10))-2)*26)));
    const height=84+([...p.slug].reduce((n,c)=>(n*31+c.charCodeAt(0))>>>0,7)%15);
    return `<a class="book t${i*3%10}" href="${p.url}" data-route="${p.url}" data-slug="${p.slug}" style="--bw:${width}px;--bh:${height}%" title="${esc(p.title)}"><span class="book-title">${esc(p.title)}</span><span class="book-mini-seal" aria-hidden="true"></span><span class="book-label">${esc(p.date)}</span></a>`;
  }).join('\n');
  const shelf = `<div class="shelf-head"><h1 tabindex="-1">书架</h1><span class="count">共 ${posts.length} 册</span><a class="m-nav" href="/blog/photos/" data-route="/blog/photos/">去暗房 →</a></div>
<div class="bookcase"><div class="case-inner"><div class="books">${items}</div><div class="plank"></div></div></div>
<div class="shelf-note">书脊厚度 = 篇幅 · 横向滑动浏览 · 抽出一本开始阅读</div>`;
  write('blog/index.html',page({title:'颗粒 · Max Xiang',description:site.description,url:'/blog/',content:shelf,kind:'shelf'}));
  for (const [i,p] of posts.entries()) {
    const prev=posts[i+1],next=posts[i-1];
    const link=(other,label)=>other?`<a href="${other.url}" data-route="${other.url}">${label} · ${esc(other.title)}</a>`:'';
    const article = `<article class="reader" data-slug="${p.slug}">
<div class="reader-nav"><a href="/blog/" data-route="/blog/" data-close="${p.slug}">← 书架</a><span>${esc(p.date)}</span></div>
<h1 class="post-title" tabindex="-1">${esc(p.title)}</h1>
<div class="post-meta">${p.count.toLocaleString('en-US')} 字 · 约 ${Math.max(1,Math.round(p.count/450))} 分钟</div>
<div class="post-body${p.poem?' poem':''}">${marked.parse(p.body)}</div>
<div class="fin">完</div><div class="fin-seal" aria-hidden="true">颗粒</div>
<div class="reader-foot"><span>${link(prev,'← 上一篇')}</span><span>${link(next,'下一篇 →')}</span></div>
</article>`;
    write('blog/posts/'+p.slug+'/index.html',page({title:p.title+' · 颗粒',url:p.url,image:p.image,type:'article',content:article,kind:'post'}));
    await cover(p.title,p.date,p.image.slice(1),i*3%10);
  }
  const photos=JSON.parse(read('content/photos.json'));
  for(const photo of photos) if (!photo.src.startsWith('/blog/photos/') || !fs.existsSync(path.join(root,photo.src.slice(1)))) throw new Error('Missing photo: '+photo.src);
  write('assets/photos.js','window.PHOTOS = '+JSON.stringify(photos).replace(/</g,'\\u003c')+';\n');
  const photoFallback=`<div class="shelf-head"><h1 tabindex="-1">暗房</h1><span class="count">${photos.length} 张</span></div><div class="photo-fallback">${photos.map(p=>`<figure><a href="${esc(p.src)}"><img src="${esc(p.src)}" alt="${esc(p.caption)}" loading="lazy"></a><figcaption>${esc(p.caption)}</figcaption></figure>`).join('')}</div>`;
  write('blog/photos/index.html',page({title:'暗房 · 颗粒',description:'Max Xiang 的摄影暗房：城市、车站与日常里的光。',url:'/blog/photos/',content:photoFallback,kind:'photos'}));
  await cover('物件、动作、温度、声音','写作 · 摄影','assets/share/grain.png',0);
  write('blog/posts/manifest.json',JSON.stringify(posts.map(p=>p.slug),null,2)+'\n');
  const urls=['/','/blog/','/blog/photos/',...posts.map(p=>p.url)];
  write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>`  <url><loc>${esc(origin+u)}</loc></url>`).join('\n')+'\n</urlset>\n');
  write('robots.txt','User-agent: *\nAllow: /\n\nSitemap: '+origin+'/sitemap.xml\n');
  console.log(`Built ${posts.length} independent articles, shelf, darkroom, and ${posts.length+1} PNG share images.`);
}
if(require.main === module) build().catch(error=>{console.error(error);process.exitCode=1;});
module.exports={parsePost,build};
